### ISSUE TITLE
import YouTube playlists

### ISSUE THREAD

**Issue by select** [select/audius#4]
Detect and import YouTube playlist URLs

**Comment by jjgh** [comment]
Hi, how progress is going on this one? thank you!

**Comment by select** [comment]
Hi there, I actually wrote this with a friend as an exercise so it's simple to do it again. I was on summer holidays and slowly starting again. This will be the next feature I add, since you "upvoted" :D

**Comment by jjgh** [comment]
Great! :) And I hope this project will get even more traction, best of luck with it!

**Comment by select** [comment]
Thanks, and if you feel some other features are important to you let me know and I'll tell if and how fast I can add them.
